Repository probe-rs/probe-rs, pull requests merged in 2021-11, with the labels that each got.

#874 Fix a typo in debugger help text
  cli/src/debugger.rs
  debugger/src/debugger.rs
Labels: skip-changelog

#875 Debugger: Do not crash CLI on empty lines
  CHANGELOG.md
  debugger/src/debug_adapter.rs
Labels: bug

#873 Debugger: Do not panic when using a command without arguments
  CHANGELOG.md
  debugger/src/dap_types.rs
  debugger/src/debug_adapter.rs
Labels: bug

#905 Release v0.12.0
  CHANGELOG.md
  cli/Cargo.toml
  debugger/Cargo.toml
  gdb-server/Cargo.toml
  probe-rs-cli-util/Cargo.toml
  probe-rs-target/Cargo.toml
  probe-rs/Cargo.toml
  rtt/Cargo.toml
  rtthost/Cargo.toml
  target-gen/Cargo.toml
Labels: release
