Repository probe-rs/probe-rs, pull requests merged in 2021-05, with the labels that each got.

#609 Fix 8 bit reads on ST-Link
  probe-rs/src/probe/stlink/mod.rs
Labels: probe:stlink

#629 Improve tracking of core status
  probe-rs/src/architecture/arm/core/m0.rs
  probe-rs/src/architecture/arm/core/m33.rs
  probe-rs/src/architecture/arm/core/m4.rs
  probe-rs/src/architecture/arm/core/mod.rs
  probe-rs/src/core/mod.rs
Labels: architecture:arm

#428 Make CHANGELOG changes mandatory in PRs
  .github/bors.toml
  .github/workflows/ci.yml
Labels: skip-changelog

#636 Automated release
  .cargo/config.toml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Cargo.toml
  doc/release.md
  xtask/Cargo.toml
  xtask/src/main.rs
Labels: skip-changelog

#642 0.11.0-alpha.0
  CHANGELOG.md
  cli/Cargo.toml
  debugger/Cargo.toml
  gdb-server/Cargo.toml
  probe-rs-cli-util/Cargo.toml
  probe-rs-target/Cargo.toml
  probe-rs/Cargo.toml
Labels: release

#643 Only check changelog entries in PR
  .github/workflows/changelog.yml
  .github/workflows/ci.yml
Labels: skip-changelog

#644 Fix libusb
  .github/workflows/release.yml
Labels: skip-changelog

#645 Release v0.11.0-alpha.1
  CHANGELOG.md
  cli/Cargo.toml
  debugger/Cargo.toml
  gdb-server/Cargo.toml
  probe-rs-cli-util/Cargo.toml
  probe-rs-target/Cargo.toml
  probe-rs/Cargo.toml
Labels: release, skip-changelog

#646 Fix fetching of PR head ref
  .github/workflows/release.yml
Labels: skip-changelog

#648 Fix inverted contains check
  .github/workflows/release.yml
Labels: skip-changelog

#647 Release v0.11.0-alpha.2
  CHANGELOG.md
  cli/Cargo.toml
  debugger/Cargo.toml
  gdb-server/Cargo.toml
  probe-rs-cli-util/Cargo.toml
  probe-rs-target/Cargo.toml
  probe-rs/Cargo.toml
Labels: release, skip-changelog

#651 Release v0.11.0-alpha.3
  cli/Cargo.toml
  debugger/Cargo.toml
  gdb-server/Cargo.toml
  probe-rs-cli-util/Cargo.toml
  probe-rs-target/Cargo.toml
  probe-rs/Cargo.toml
Labels: release

#652 Remove 'v' from branch extraction
  .github/workflows/release.yml
Labels: skip-changelog

#653 Release v0.11.0-alpha.4
  cli/Cargo.toml
  debugger/Cargo.toml
  gdb-server/Cargo.toml
  probe-rs-cli-util/Cargo.toml
  probe-rs-target/Cargo.toml
  probe-rs/Cargo.toml
Labels: release

#654 Release v0.11.0-alpha.5
  cli/Cargo.toml
  debugger/Cargo.toml
  gdb-server/Cargo.toml
  probe-rs-cli-util/Cargo.toml
  probe-rs-target/Cargo.toml
  probe-rs/Cargo.toml
Labels: release

#658 Update jaylink to version 0.2.0
  probe-rs/Cargo.toml
  probe-rs/src/probe/jlink/mod.rs
Labels: skip-changelog

#657 Add RISCV debug spec to resources, reorganize resources file.
  RESOURCES.md
Labels: skip-changelog

#659 Fix build without built-in targets
  .github/workflows/ci.yml
  probe-rs/src/config/registry.rs
Labels: skip-changelog
