Repository probe-rs/probe-rs, pull requests merged in 2021-06, with the labels that each got.

#663 Fix typo "openend"
  probe-rs/src/probe/stlink/mod.rs
Labels: skip-changelog

#661 Fix RISCV assembly generation, source and destination in lw instruction was switched
  probe-rs/src/architecture/riscv/assembly.rs
  probe-rs/src/architecture/riscv/communication_interface.rs
Labels: skip-changelog

#667 riscv: Fix single word write using progbuf
  probe-rs/src/architecture/riscv/communication_interface.rs
Labels: skip-changelog

#695 Fix HNONSEC being hardcoded to false.
  probe-rs/src/architecture/arm/communication_interface.rs
Labels: needs-changelog

#690 Basic smoke testing tool
  Cargo.toml
  smoke-tester/Cargo.toml
  smoke-tester/README.md
  smoke-tester/create_assembly.sh
  smoke-tester/src/dut_definition.rs
  smoke-tester/src/main.rs
  smoke-tester/src/tests.rs
  smoke-tester/src/tests/stepping.rs
  smoke-tester/src/tests/test_arm.bin
  smoke-tester/test_function_arm.s
Labels: skip-changelog

#696 Add rerun-if-changed to build.rs to avoid unnecessary reruns.
  probe-rs/build.rs
Labels: skip-changelog

#698 stlink: remove unused imports
  probe-rs/src/probe/stlink/mod.rs
Labels: skip-changelog

#705 Simplify DownloadOptions, fix #684
  debugger/src/debugger.rs
  probe-rs/src/flashing/download.rs
  smoke-tester/src/tests.rs
Labels: skip-changelog

#708 Fix support for 'dry run' functionality for flashing
  probe-rs/src/flashing/loader.rs
  probe-rs/src/probe.rs
  probe-rs/tests/flash_dry_run.rs
Labels: skip-changelog

#709 Remove itm-decode dependency, don't build sentry by default
  probe-rs-cli-util/Cargo.toml
  probe-rs/Cargo.toml
  probe-rs/examples/tcp_itm.rs
  probe-rs/src/architecture/arm/swo/mod.rs
Labels: skip-changelog

#711 Release v0.11.0
  CHANGELOG.md
  cli/Cargo.toml
  debugger/Cargo.toml
  gdb-server/Cargo.toml
  probe-rs-cli-util/Cargo.toml
  probe-rs-target/Cargo.toml
  probe-rs/Cargo.toml
  smoke-tester/Cargo.toml
Labels: release

#713 Mark smoke-tester package as private, create draft PR for release, update release docs
  doc/release.md
  smoke-tester/Cargo.toml
  xtask/src/main.rs
Labels: skip-changelog

#714 Small review fixes
  debugger/README.md
  smoke-tester/README.md
Labels: skip-changelog
