Repository probe-rs/probe-rs, pull requests merged in 2024-10, with the labels that each got.

#2839 Ensure that we can't queue more bits than the buffer can hold
  probe-rs/src/probe/espusbjtag/protocol.rs
Labels: skip-changelog

#2842 Remove once_cell dependency
  Cargo.lock
  probe-rs-tools/Cargo.toml
  probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/request_helpers.rs
  probe-rs-tools/src/bin/probe-rs/util/logging.rs
  probe-rs/Cargo.toml
  probe-rs/src/architecture/arm/core/registers/aarch32.rs
  probe-rs/src/architecture/arm/core/registers/aarch64.rs
  probe-rs/src/architecture/arm/core/registers/cortex_m.rs
  probe-rs/src/architecture/riscv/registers.rs
  probe-rs/src/architecture/xtensa/registers.rs
  probe-rs/src/config/registry.rs
  probe-rs/src/probe/stlink/usb_interface.rs
  probe-rs/src/vendor/mod.rs
Labels: skip-changelog

#2843 Update rust version
  probe-rs-tools/src/bin/probe-rs/util/rtt.rs
  probe-rs/src/architecture/arm/ap/memory_ap/amba_ahb3.rs
  probe-rs/src/architecture/arm/ap/memory_ap/amba_ahb5.rs
  probe-rs/src/architecture/arm/ap/memory_ap/amba_ahb5_hprot.rs
  probe-rs/src/architecture/arm/ap/memory_ap/amba_apb2_apb3.rs
  probe-rs/src/architecture/arm/ap/memory_ap/amba_apb4_apb5.rs
  probe-rs/src/architecture/arm/ap/memory_ap/amba_axi3_axi4.rs
  probe-rs/src/architecture/arm/ap/memory_ap/amba_axi5.rs
  probe-rs/src/architecture/xtensa/arch/instruction/mod.rs
  probe-rs/src/architecture/xtensa/communication_interface.rs
  probe-rs/src/architecture/xtensa/xdm.rs
  rust-toolchain.toml
Labels: skip-changelog

#2744 RiscV: fix reading wide data, various small changes
  probe-rs/src/architecture/riscv/communication_interface.rs
  probe-rs/src/architecture/riscv/mod.rs
  probe-rs/src/flashing/flasher.rs
  probe-rs/src/session.rs
Labels: bug, skip-changelog

#2856 Update zerocopy to version 0.8.0
  Cargo.lock
  probe-rs/Cargo.toml
  probe-rs/src/rtt.rs
  probe-rs/src/rtt/channel.rs
Labels: skip-changelog

#2857 target/ch32v3: add ch32v305 variant
  probe-rs/targets/CH32V3_Series.yaml
Labels: needs-changelog

#2868 Adding MSPM0GX targets
  probe-rs/targets/MSPM0G1X0X_G3X0X_Series.yaml
Labels: needs-changelog

#2871 Use Rust 1.82 in CI
  rust-toolchain.toml
Labels: skip-changelog

#2866 Handle relative file paths in smoke-test configuration
  smoke-tester/src/dut_definition.rs
Labels: skip-changelog
