Repository probe-rs/probe-rs, pull requests merged in 2024-05, with the labels that each got.

#2357 Clean up subcommand argument processing
  probe-rs-tools/src/bin/cargo-embed.rs
  probe-rs-tools/src/bin/cargo-flash.rs
  probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
  probe-rs-tools/src/bin/probe-rs/cmd/cargo_flash/mod.rs
  probe-rs-tools/src/bin/probe-rs/main.rs
Labels: skip-changelog, hygiene

#2417 Disable all DPs but only when disconnecting
  probe-rs/src/architecture/arm/communication_interface.rs
  probe-rs/src/architecture/arm/sequences.rs
Labels: skip-changelog

#2419 Update Embed.toml flashing options
  changelog/added-embed-config-opts.md
  changelog/removed-halt_afterwards.md
  probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/config/default.toml
  probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/config/mod.rs
  probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
Labels: component:cargo-embed

#2421 Cleanup variable handling & formatting part 1
  probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
  probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/repl_commands_helpers.rs
  probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/request_helpers.rs
  probe-rs-tools/src/bin/probe-rs/cmd/debug.rs
  probe-rs/Cargo.toml
  probe-rs/src/debug/language.rs
  probe-rs/src/debug/unit_info.rs
  probe-rs/src/debug/variable.rs
  probe-rs/src/debug/variable_cache.rs
  probe-rs/src/domain.rs
Labels: skip-changelog

#2418 Pass Session to ESP flash size detection
  probe-rs/src/architecture/riscv/sequences.rs
  probe-rs/src/architecture/xtensa/sequences.rs
  probe-rs/src/config/sequences/esp.rs
  probe-rs/src/config/sequences/esp32.rs
  probe-rs/src/config/sequences/esp32c2.rs
  probe-rs/src/config/sequences/esp32c3.rs
  probe-rs/src/config/sequences/esp32c6.rs
  probe-rs/src/config/sequences/esp32h2.rs
  probe-rs/src/config/sequences/esp32s2.rs
  probe-rs/src/config/sequences/esp32s3.rs
  probe-rs/src/flashing/loader.rs
Labels: skip-changelog

#2427 Target cleanup & related fixes
  probe-rs-target/src/chip_family.rs
  probe-rs/targets/BCM2711.yaml
  probe-rs/targets/BCM2712.yaml
  probe-rs/targets/CC13XX_CC26XX_Series.yaml
  probe-rs/targets/GD32VF1_Series.yaml
  probe-rs/targets/HC32F005-Series.yaml
  probe-rs/targets/LPC55S16.yaml
  probe-rs/targets/MIMXRT1010.yaml
  probe-rs/targets/MIMXRT1015.yaml
  probe-rs/targets/MIMXRT1020.yaml
  probe-rs/targets/MIMXRT1050.yaml
  probe-rs/targets/MIMXRT1060.yaml
  probe-rs/targets/MIMXRT1064.yaml
  probe-rs/targets/MIMXRT1170.yaml
  probe-rs/targets/MSP432P4XX_Series.yaml
  probe-rs/targets/OpenTitan.yaml
  probe-rs/targets/SAM3U.yaml
  probe-rs/targets/SAM4_Series.yaml
  probe-rs/targets/SAMD10.yaml
  probe-rs/targets/SAMD11.yaml
  probe-rs/targets/SAMD21.yaml
  probe-rs/targets/SAMD51.yaml
  probe-rs/targets/SAMDA1.yaml
  probe-rs/targets/SAME51.yaml
  probe-rs/targets/SAME53.yaml
  probe-rs/targets/SAME54.yaml
  probe-rs/targets/STM32F2_Series.yaml
  probe-rs/targets/STM32F4_Series.yaml
  probe-rs/targets/STM32F7_Series.yaml
  probe-rs/targets/STM32L0_Series.yaml
  probe-rs/targets/STM32L1_Series.yaml
  probe-rs/targets/STM32L4_Series.yaml
  probe-rs/targets/esp32c6_lp.yaml
  probe-rs/targets/fe310.yaml
  probe-rs/targets/iMX7ULP.yaml
  probe-rs/tests/scan_chain_test.yaml
Labels: skip-changelog

#2429 Only check our own documentation
  .github/workflows/ci.yml
Labels: skip-changelog, ci

#2428 Small target-gen cleanup
  target-gen/src/commands/elf.rs
  target-gen/src/generate.rs
  target-gen/src/main.rs
  target-gen/src/parser.rs
Labels: skip-changelog

#2433 Fix target-gen serialize
  target-gen/src/commands/elf.rs
Labels: skip-changelog

#2432 Remove direct use of num-traits, remove unused and trivial deps
  Cargo.lock
  probe-rs-tools/Cargo.toml
  probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
  probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/request_helpers.rs
  probe-rs/Cargo.toml
  probe-rs/src/architecture/arm/ap/generic_ap.rs
  probe-rs/src/architecture/arm/ap/memory_ap/mod.rs
  probe-rs/src/architecture/arm/core/armv7a.rs
  probe-rs/src/architecture/arm/core/exception_handling/armv6m_armv7m_shared.rs
  probe-rs/src/architecture/arm/memory/romtable.rs
  probe-rs/src/debug/language/parsing.rs
  probe-rs/src/debug/variable.rs
  probe-rs/src/probe/jlink/speed.rs
  probe-rs/src/probe/jlink/swo.rs
  probe-rs/src/probe/stlink/constants.rs
  xtask/Cargo.toml
Labels: skip-changelog

#2438 Drop unnecessary changelog entries
  changelog/changed-update-cmsis-pack-0.7.0.md
  changelog/fixed-rust-toolchain.md
Labels: skip-changelog

#2437 Fix swm341 ram size too large issue
  probe-rs/targets/SWM341.yaml
Labels: skip-changelog

#2443 Smoke tester: allow setting probe speed
  smoke-tester/src/dut_definition.rs
  smoke-tester/src/main.rs
Labels: skip-changelog

#2460 `halted_access`: Only read cpu status once
  probe-rs/src/session.rs
Labels: skip-changelog

#2465 Only set intlevel on reset
  probe-rs/src/architecture/xtensa/communication_interface.rs
  probe-rs/src/architecture/xtensa/sequences.rs
Labels: bug, chip:esp32, architecture:xtensa

#2415 Rebase of #2119 and some related cleanups
  probe-rs/src/architecture/arm/sequences.rs
  probe-rs/src/architecture/riscv/mod.rs
  probe-rs/src/config/sequences/nxp_armv7m.rs
  probe-rs/src/config/sequences/nxp_armv8m.rs
  probe-rs/src/probe/arm_debug_interface.rs
Labels: skip-changelog

#2467 probe: add probe_type() to DebugProbeInfo.
  probe-rs/src/probe.rs
Labels: skip-changelog

#2468 Change probe info format
  probe-rs/src/probe.rs
  probe-rs/src/probe/jlink/mod.rs
Labels: skip-changelog

#2461 `probe-rs info` improvements & corrections
  probe-rs-tools/src/bin/probe-rs/cmd/info.rs
  probe-rs/src/architecture/arm/component/scs.rs
  probe-rs/src/architecture/arm/memory/mod.rs
  probe-rs/src/architecture/arm/memory/romtable.rs
  probe-rs/src/config/sequences/atsam.rs
Labels: skip-changelog

#2474 Registry: use parking_lot, allow reading families without cloning them
  probe-rs/Cargo.toml
  probe-rs/src/config/mod.rs
  probe-rs/src/config/registry.rs
Labels: skip-changelog

#2481 Fix stlink `swj_sequence` typo
  probe-rs/src/probe/stlink/mod.rs
Labels: skip-changelog

#2478 Allow recursive access to the registry
  probe-rs/src/config/registry.rs
Labels: skip-changelog

#2482 Fix deprecated config filename, revert yanked cortex-m-rt
  probe-rs-tools/src/bin/probe-rs/util/test_data/binary_cargo_config/.cargo/config.toml
  probe-rs-tools/src/bin/probe-rs/util/test_data/binary_cargo_config/Cargo.toml
  probe-rs-tools/src/bin/probe-rs/util/test_data/binary_cargo_config_toml/Cargo.toml
Labels: skip-changelog

#2479 Better error messages for CMSIS-DAP probes
  changelog/fixed-cmsis-dap-error-reporting.md
  probe-rs-tools/src/bin/probe-rs/util/common_options.rs
  probe-rs/src/architecture/arm/mod.rs
  probe-rs/src/architecture/arm/sequences.rs
  probe-rs/src/probe.rs
  probe-rs/src/session.rs
Labels: skip-changelog, hygiene

#2483 Clean up
  probe-rs/src/architecture/arm/sequences.rs
Labels: skip-changelog

#2431 Update docs based on restructuring
  CONTRIBUTING.md
  README.md
  probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
Labels: skip-changelog

#2485 Update defmt-decoder
  Cargo.lock
  probe-rs-tools/Cargo.toml
Labels: skip-changelog

#2486 Update install instructions
  README.md
Labels: skip-changelog

#2489 Add missing features to mi
  probe-rs-mi/Cargo.toml
Labels: skip-changelog

#2494 Change the CI error message if CHANGELOG.md is edited
  xtask/src/main.rs
Labels: skip-changelog

#2499 Do not bump mi version on release
  .github/workflows/start-release.yml
Labels: skip-changelog

#2504 Comment on PR if changelog is edited
  .github/workflows/changelog.yml
  xtask/src/main.rs
Labels: skip-changelog

#2500 Clean up probe selection
  probe-rs-tools/src/bin/probe-rs/util/common_options.rs
Labels: skip-changelog, hygiene

#2503 Prefix mi release tags
  .github/workflows/release_crates.yml
  .github/workflows/v-release.yml
  Cargo.toml
Labels: skip-changelog

#2501 Delete empty file
  cargo
Labels: skip-changelog

#2507 Rtt initialization cleanup
  probe-rs/src/rtt.rs
  probe-rs/src/rtt/channels.rs
Labels: skip-changelog, hygiene

#2508 Clean up Memory region related code
  Cargo.lock
  probe-rs-target/src/memory.rs
  probe-rs-tools/Cargo.toml
  probe-rs-tools/src/bin/probe-rs/cmd/cargo_flash/diagnostics.rs
  probe-rs-tools/src/bin/probe-rs/cmd/chip.rs
  probe-rs-tools/src/bin/probe-rs/cmd/snapshots/probe_rs__cmd__chip__single_chip_output.snap
  probe-rs/src/flashing/erase.rs
  probe-rs/src/flashing/flasher.rs
  probe-rs/src/gdb_server/target/desc/mod.rs
  probe-rs/src/rtt/channel.rs
  smoke-tester/src/tests.rs
Labels: skip-changelog, hygiene

#2512 Updated installation links
  README.md
Labels: skip-changelog

#2511 Trim dependency features, clean up some code
  Cargo.lock
  probe-rs-tools/Cargo.toml
  probe-rs-tools/src/bin/probe-rs/cmd/benchmark.rs
  probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
  probe-rs-tools/src/bin/probe-rs/cmd/cargo_flash/diagnostics.rs
  probe-rs-tools/src/bin/probe-rs/cmd/cargo_flash/mod.rs
  probe-rs-tools/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/dap_types.rs
  probe-rs-tools/src/bin/probe-rs/cmd/dap_server/mod.rs
  probe-rs-tools/src/bin/probe-rs/cmd/debug.rs
  probe-rs/Cargo.toml
  probe-rs/examples/ram_download.rs
  probe-rs/src/architecture/arm/component/itm.rs
  probe-rs/src/architecture/arm/component/scs.rs
  probe-rs/src/core/memory_mapped_registers.rs
  probe-rs/src/session.rs
  target-gen/Cargo.toml
  target-gen/tests/extract_pack.rs
Labels: skip-changelog, hygiene

#2521 target-gen: Import from probe-rs-target directly
  target-gen/src/algorithm_binary.rs
  target-gen/src/commands/elf.rs
  target-gen/src/commands/test.rs
  target-gen/src/generate.rs
  target-gen/src/main.rs
  target-gen/src/parser.rs
Labels: skip-changelog, hygiene
