Repository probe-rs/probe-rs, pull requests merged in 2024-04, with the labels that each got.

#2334 remove redundant turbo-fishes
  probe-rs/src/architecture/arm/core/armv7m.rs
  probe-rs/src/architecture/arm/core/armv8m.rs
  probe-rs/src/probe/cmsisdap/mod.rs
Labels: skip-changelog

#2355 Some more RTT churn
  probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/server/core_data.rs
  probe-rs/src/bin/probe-rs/cmd/run/mod.rs
  probe-rs/src/bin/probe-rs/util/rtt.rs
  probe-rs/src/flashing/flasher.rs
  probe-rs/src/rtt.rs
Labels: skip-changelog

#2344 Add `--skip-test` argument to CLI
  probe-rs/src/bin/probe-rs/cmd/run/test_run_mode.rs
Labels: skip-changelog

#2345 Use docsplay for RegistryError
  probe-rs/src/bin/probe-rs/cmd/cargo_flash/diagnostics.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/repl_commands.rs
  probe-rs/src/config/registry.rs
  probe-rs/src/config/target.rs
  probe-rs/src/flashing/erase.rs
  probe-rs/src/flashing/error.rs
  probe-rs/src/flashing/loader.rs
Labels: skip-changelog

#2361 run/attach: Only halt if we have to
  probe-rs/src/bin/probe-rs/cmd/run/mod.rs
Labels: skip-changelog

#2350 Don't generate meta.rs file
  probe-rs/build.rs
  probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
  probe-rs/src/bin/probe-rs/cmd/cargo_flash/mod.rs
  probe-rs/src/bin/probe-rs/main.rs
Labels: skip-changelog

#2367 Remove deprecated uses of `time::Instant`
  probe-rs/src/bin/probe-rs/cmd/profile.rs
Labels: skip-changelog, hygiene

#2363 Only read CWD once instead of on every RTT poll event
  probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/channel.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/server/core_data.rs
  probe-rs/src/bin/probe-rs/util/rtt.rs
Labels: skip-changelog

#2372 Update to gimli 0.29.0
  Cargo.lock
  probe-rs/Cargo.toml
  probe-rs/src/debug/debug_info.rs
Labels: skip-changelog

#2368 Registry cleanup
  probe-rs/src/config/registry.rs
Labels: skip-changelog, hygiene

#2318 Update cargo-dist to v0.13, enable ARM builds again
  .github/workflows/release.yml
  Cargo.toml
Labels: skip-changelog

#2365 RISC-V reset sequences
  changelog/fixed-esp32-riscv-reset.md
  probe-rs/src/architecture/riscv/communication_interface.rs
  probe-rs/src/architecture/riscv/dtm/dtm_access.rs
  probe-rs/src/architecture/riscv/dtm/jtag_dtm.rs
  probe-rs/src/architecture/riscv/mod.rs
  probe-rs/src/architecture/riscv/sequences.rs
  probe-rs/src/architecture/xtensa/communication_interface.rs
  probe-rs/src/architecture/xtensa/mod.rs
  probe-rs/src/architecture/xtensa/sequences.rs
  probe-rs/src/architecture/xtensa/xdm.rs
  probe-rs/src/bin/probe-rs/cmd/run/mod.rs
  probe-rs/src/config/sequences/esp.rs
  probe-rs/src/config/sequences/esp32.rs
  probe-rs/src/config/sequences/esp32c2.rs
  probe-rs/src/config/sequences/esp32c3.rs
  probe-rs/src/config/sequences/esp32c6.rs
  probe-rs/src/config/sequences/esp32h2.rs
  probe-rs/src/config/sequences/esp32s2.rs
  probe-rs/src/config/sequences/esp32s3.rs
  probe-rs/src/core.rs
  probe-rs/src/core/core_state.rs
  probe-rs/src/probe.rs
  probe-rs/src/probe/arm_debug_interface.rs
  probe-rs/src/probe/common.rs
  probe-rs/src/probe/wlink/mod.rs
  probe-rs/src/session.rs
Labels: enhancement, architecture:riscv, component:probe-rs

#2370 Provide a bit more info in some low-level Xtensa errors
  probe-rs/src/architecture/riscv/dtm/jtag_dtm.rs
  probe-rs/src/architecture/xtensa/communication_interface.rs
  probe-rs/src/architecture/xtensa/xdm.rs
  probe-rs/src/probe.rs
  probe-rs/src/probe/common.rs
Labels: skip-changelog

#2380 smoke-tester: normalize chip name to lower case
  .github/workflows/smoketest.yml
  probe-rs/targets/esp32c6.yaml
  smoke-tester/README.md
  smoke-tester/src/dut_definition.rs
Labels: skip-changelog

#2375 Use as much stack as possible for the flash loader
  probe-rs/src/flashing/flash_algorithm.rs
  probe-rs/targets/BCM2711.yaml
  probe-rs/targets/BCM2712.yaml
  probe-rs/targets/esp32c6.yaml
  probe-rs/targets/esp32c6_lp.yaml
  probe-rs/targets/esp32h2.yaml
  probe-rs/targets/iMX7ULP.yaml
Labels: skip-changelog

#2339 Try out some smoke tester improvements
  .github/workflows/smoketest.yml
  Cargo.lock
  smoke-tester/Cargo.toml
  smoke-tester/src/dut_definition.rs
  smoke-tester/src/macros.rs
  smoke-tester/src/main.rs
  smoke-tester/src/tests.rs
  smoke-tester/src/tests/stepping.rs
Labels: skip-changelog

#2381 Unbreak Xtensa
  probe-rs/src/architecture/xtensa/communication_interface.rs
  probe-rs/src/architecture/xtensa/mod.rs
  probe-rs/src/architecture/xtensa/sequences.rs
  probe-rs/src/config/sequences/esp.rs
Labels: skip-changelog

#2390 Fix typo
  probe-rs/src/probe/jlink/interface.rs
Labels: skip-changelog

#2378 ATSAM: bring out of reset extension
  probe-rs/src/config/sequences/atsam.rs
Labels: skip-changelog, chip:atsam

#2391 Add second smoke tester and fix flash testing ESP devices
  .github/workflows/smoketest.yml
  Cargo.lock
  smoke-tester/Cargo.toml
  smoke-tester/src/tests.rs
Labels: skip-changelog

#2388 Slightly clean up the Xtensa code
  probe-rs/src/architecture/xtensa/communication_interface.rs
  probe-rs/src/architecture/xtensa/mod.rs
  probe-rs/src/architecture/xtensa/xdm.rs
Labels: skip-changelog

#2395 cargo-embed: Don't panic if no binary data was read
  probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/tab.rs
Labels: skip-changelog

#2394 Make sure all bytes make it to the TcpStream
  probe-rs/src/bin/probe-rs/cmd/cargo_embed/rttui/tcp.rs
Labels: skip-changelog

#2393 smoke-tester: print flashing progress to stdout
  smoke-tester/src/tests.rs
Labels: skip-changelog

#2377 Remove default rtt options, remove channel name configuration
  changelog/changed-rtt-defaults.md
  probe-rs/src/bin/probe-rs/cmd/cargo_embed/config/default.toml
  probe-rs/src/bin/probe-rs/cmd/cargo_embed/config/mod.rs
  probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
  probe-rs/src/bin/probe-rs/util/rtt.rs
Labels: component:cargo-embed, component:debugger

#2406 RISC-V: Cache the hw breakpoint count
  probe-rs/src/architecture/riscv/mod.rs
Labels: architecture:riscv, skip-changelog

#2411 Fix flashing RISC-V chips after setting breakpoints
  probe-rs/src/architecture/riscv/mod.rs
Labels: architecture:riscv, skip-changelog

#2402 Fix flashing ESP32-C2 and C3
  probe-rs/src/architecture/riscv/communication_interface.rs
  probe-rs/src/config/sequences/esp32c3.rs
  probe-rs/src/flashing/flash_algorithm.rs
  probe-rs/src/flashing/flasher.rs
  probe-rs/src/probe/ftdi/mod.rs
  probe-rs/targets/esp32c2.yaml
  probe-rs/targets/esp32c3.yaml
Labels: skip-changelog

#2404 Smoke tester: do not pass test suite with failing tests
  smoke-tester/src/dut_definition.rs
  smoke-tester/src/main.rs
  smoke-tester/src/tests.rs
Labels: skip-changelog

#2386 Support multiple debug modules in the same target
  changelog/added-jtag-tap.md
  changelog/changed-interfaces.md
  probe-rs-target/src/chip.rs
  probe-rs-tools/src/bin/probe-rs/cmd/info.rs
  probe-rs/src/architecture/riscv/communication_interface.rs
  probe-rs/src/architecture/riscv/dtm/dtm_access.rs
  probe-rs/src/architecture/riscv/dtm/jtag_dtm.rs
  probe-rs/src/architecture/riscv/mod.rs
  probe-rs/src/architecture/xtensa/communication_interface.rs
  probe-rs/src/architecture/xtensa/mod.rs
  probe-rs/src/architecture/xtensa/xdm.rs
  probe-rs/src/config/registry.rs
  probe-rs/src/core.rs
  probe-rs/src/core/core_state.rs
  probe-rs/src/flashing/loader.rs
  probe-rs/src/probe.rs
  probe-rs/src/probe/arm_debug_interface.rs
  probe-rs/src/probe/cmsisdap/mod.rs
  probe-rs/src/probe/common.rs
  probe-rs/src/probe/espusbjtag/mod.rs
  probe-rs/src/probe/fake_probe.rs
  probe-rs/src/probe/ftdi/mod.rs
  probe-rs/src/probe/jlink/mod.rs
  probe-rs/src/probe/stlink/mod.rs
  probe-rs/src/probe/wlink/mod.rs
  probe-rs/src/session.rs
  probe-rs/targets/esp32.yaml
  probe-rs/targets/esp32s3.yaml
  target-gen/src/generate.rs
Labels: needs-changelog

#2405 Simplify writing Xtensa instruction sequences
  probe-rs/src/architecture/xtensa/arch/instruction/mod.rs
  probe-rs/src/architecture/xtensa/mod.rs
  probe-rs/src/config/sequences/esp.rs
Labels: skip-changelog
