Repository probe-rs/probe-rs, pull requests merged in 2024-02, with the labels that each got.

#2128 Downgrade debug log that should not be a warning
  probe-rs/src/architecture/riscv/mod.rs
Labels: skip-changelog

#2120 Exit retry loop when using JTAG
  probe-rs/src/architecture/arm/sequences.rs
Labels: skip-changelog

#2129 Don't panic if `current_local_offset` fails
  probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
  probe-rs/src/bin/probe-rs/main.rs
Labels: skip-changelog

#2107 update nusb, attempt to detach ftdi drivers
  Cargo.lock
  probe-rs/src/probe/ftdi/ftdaye/mod.rs
Labels: skip-changelog

#2093 Simplify `FlashAlgorithm::assemble_from_raw`
  probe-rs/src/flashing/error.rs
  probe-rs/src/flashing/flash_algorithm.rs
Labels: skip-changelog, hygiene

#2142 Deduplicate `resolve_cwd`
  probe-rs/src/bin/probe-rs/cmd/dap_server/server/configuration.rs
Labels: skip-changelog

#2141 Fix cargo subcommand build instructions
  CONTRIBUTING.md
Labels: skip-changelog

#2159 Fix clippy warning, use rustc 1.76
  .github/actions/setup/action.yml
  probe-rs/examples/tcp_itm.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/server/core_data.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/server/session_data.rs
Labels: skip-changelog

#2157 Unwind C enum variants, handle all C versions known by gimli, fix struct members
  probe-rs/src/debug/language.rs
  probe-rs/src/debug/language/c.rs
  probe-rs/src/debug/language/rust.rs
  probe-rs/src/debug/mod.rs
  probe-rs/src/debug/unit_info.rs
Labels: skip-changelog

#2166 Remove unused code
  probe-rs/src/architecture/riscv/communication_interface.rs
  probe-rs/src/probe/common.rs
  probe-rs/src/probe/espusbjtag/mod.rs
  probe-rs/src/probe/ftdi/mod.rs
  probe-rs/src/probe/jlink/mod.rs
Labels: skip-changelog

#2167 Update defmt_decoder
  Cargo.lock
  probe-rs/Cargo.toml
  probe-rs/src/bin/probe-rs/util/rtt.rs
Labels: dependencies, skip-changelog

#2172 ADIv5: Fix a bunch of mistakes in `ArmProbe::write`
  probe-rs/src/architecture/arm/ap/memory_ap/mock.rs
  probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
Labels: skip-changelog

#2175 Clean up variable value parsing
  probe-rs/Cargo.toml
  probe-rs/src/debug/language.rs
  probe-rs/src/debug/language/c.rs
  probe-rs/src/debug/language/parsing.rs
  probe-rs/src/debug/language/rust.rs
  probe-rs/src/debug/language/value.rs
Labels: skip-changelog

#2176 Fix svd bug
  probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
Labels: skip-changelog

#2177 Do not debug-print VariableType variant when hovering over a variable
  probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/repl_commands_helpers.rs
Labels: skip-changelog

#2179 Some more misc cleanup
  probe-rs/src/debug/mod.rs
  probe-rs/src/debug/unit_info.rs
  probe-rs/src/debug/variable.rs
  probe-rs/src/debug/variable_cache.rs
Labels: skip-changelog

#2158 Update cargo install command in the readme to use Cargo.lock
  README.md
Labels: skip-changelog

#2186 debug: Simplify namespace processing
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__RP2040__full_unwind.snap
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__nRF52833_xxAA__full_unwind.snap
  probe-rs/src/debug/unit_info.rs
Labels: skip-changelog

#2189 Print at least one fractional digit for floats
  probe-rs/src/debug/language/c.rs
  probe-rs/src/debug/language/rust.rs
  probe-rs/src/debug/language/value.rs
Labels: skip-changelog

#2190 Do not error if we encounter unknown attributes
  probe-rs/src/debug/unit_info.rs
Labels: skip-changelog

#2191 Avoid a few clones/allocs
  probe-rs/src/debug/debug_info.rs
  probe-rs/src/debug/language/value.rs
  probe-rs/src/debug/unit_info.rs
Labels: skip-changelog

#2192 Remove xtensa example launch config
  .vscode/launch.json
Labels: skip-changelog

#2197 Use references when evaluating variables, don't use them by value
  probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
  probe-rs/src/debug/debug_info.rs
  probe-rs/src/debug/language.rs
  probe-rs/src/debug/unit_info.rs
  probe-rs/src/debug/variable.rs
  probe-rs/src/debug/variable_cache.rs
Labels: skip-changelog

#2199 Clean up unnecessary special case, shorten errors, move rust-specific code
  probe-rs/src/debug/language.rs
  probe-rs/src/debug/language/c.rs
  probe-rs/src/debug/language/rust.rs
  probe-rs/src/debug/unit_info.rs
  probe-rs/src/debug/variable.rs
Labels: skip-changelog

#2202 Align Xtensa timeout handling to other arch's
  probe-rs/src/architecture/xtensa/communication_interface.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
  probe-rs/src/debug/debug_step.rs
Labels: skip-changelog

#2208 AArch64: Fix FPCR other name
  probe-rs/src/gdb_server/target/desc/data.rs
Labels: needs-changelog

#2209 targets: Add BCM2712(Raspberry Pi 5)
  probe-rs/targets/BCM2712.yaml
Labels: needs-changelog

#2210 Instrument a few functions
  probe-rs/src/architecture/xtensa/communication_interface.rs
  probe-rs/src/architecture/xtensa/xdm.rs
  probe-rs/src/core.rs
  probe-rs/src/probe/common.rs
Labels: skip-changelog

#2178 Improve variable typing: follow typedefs, resolve pointer types better
  probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/repl_commands_helpers.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/peripherals/svd_cache.rs
  probe-rs/src/bin/probe-rs/cmd/debug.rs
  probe-rs/src/debug/debug_info.rs
  probe-rs/src/debug/language.rs
  probe-rs/src/debug/language/c.rs
  probe-rs/src/debug/language/rust.rs
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__RP2040__full_unwind.snap
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__nRF52833_xxAA__full_unwind.snap
  probe-rs/src/debug/unit_info.rs
  probe-rs/src/debug/variable.rs
  probe-rs/src/debug/variable_cache.rs
Labels: skip-changelog

#2218 Some slightly opinionated cleanup to `formatted_variable_value`
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__RP2040__full_unwind.snap
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__RP2040__static_variables.snap
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__atsamd51p19a__static_variables.snap
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__nRF52833_xxAA__full_unwind.snap
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__nRF52833_xxAA__static_variables.snap
  probe-rs/src/debug/variable.rs
Labels: skip-changelog

#2220 Improve printing big arrays & a collection of small assorted improvements
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__RP2040__full_unwind.snap
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__RP2040__static_variables.snap
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__atsamd51p19a__full_unwind.snap
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__atsamd51p19a__static_variables.snap
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__nRF52833_xxAA__full_unwind.snap
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__nRF52833_xxAA__static_variables.snap
  probe-rs/src/debug/variable.rs
  probe-rs/src/debug/variable_cache.rs
Labels: skip-changelog

#2221 Simplify the creation of the tree iterator, remove `ReferenceOffset`
  probe-rs/src/debug/debug_info.rs
  probe-rs/src/debug/unit_info.rs
  probe-rs/src/debug/variable.rs
Labels: skip-changelog

#2181 Debug: Cleanup handling of breakpoints and stepping.
  probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/server/core_data.rs
  probe-rs/src/debug/debug_info.rs
  probe-rs/src/debug/debug_step.rs
  probe-rs/src/debug/function_die.rs
  probe-rs/src/debug/mod.rs
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__RP2040__full_unwind.snap
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__atsamd51p19a__full_unwind.snap
  probe-rs/src/debug/snapshots/probe_rs__debug__debug_info__test__nRF52833_xxAA__full_unwind.snap
  probe-rs/src/debug/source_instructions.rs
  probe-rs/src/debug/source_statement.rs
  probe-rs/src/debug/unit_info.rs
  probe-rs/tests/source_location.rs
Labels: skip-changelog

#2227 Touch up changelog
  CHANGELOG.md
  probe-rs/Cargo.toml
Labels: skip-changelog

#2233 Update cargo-dist, get rid of deprecation warnings in release workflow
  .github/workflows/release.yml
  Cargo.toml
Labels: skip-changelog

#2234 Massage the changelog a bit
  CHANGELOG.md
  xtask/src/main.rs
Labels: skip-changelog

#2235 Remove vcpkg meantion from the readme
  README.md
Labels: skip-changelog

#2239 Remove view_bits call from u64
  probe-rs/src/probe/arm_debug_interface.rs
Labels: skip-changelog

#2224 Don't accidentally disable the Risc-V debug module
  changelog/fixed-riscv-dm-disabled.md
  probe-rs/src/architecture/riscv/communication_interface.rs
  probe-rs/src/architecture/riscv/mod.rs
Labels: architecture:riscv

#2243 Don't use debug for end user output of probe types
  probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/server/debugger.rs
  probe-rs/src/bin/probe-rs/cmd/list.rs
  probe-rs/src/bin/probe-rs/util/common_options.rs
  probe-rs/src/probe.rs
  probe-rs/src/probe/cmsisdap/mod.rs
  probe-rs/src/probe/espusbjtag/mod.rs
  probe-rs/src/probe/ftdi/mod.rs
  probe-rs/src/probe/jlink/mod.rs
  probe-rs/src/probe/stlink/mod.rs
  probe-rs/src/probe/wlink/mod.rs
Labels: skip-changelog

#2244 Introduce docsplay to the codebase, clean up warnings in newest nightly
  Cargo.lock
  Cargo.toml
  probe-rs-target/src/serialize/hex_option.rs
  probe-rs-target/src/serialize/hex_range.rs
  probe-rs-target/src/serialize/hex_u_int.rs
  probe-rs/Cargo.toml
  probe-rs/src/architecture/arm/ap/memory_ap/mock.rs
  probe-rs/src/architecture/arm/ap/memory_ap/mod.rs
  probe-rs/src/architecture/arm/component/tmc.rs
  probe-rs/src/architecture/arm/core/armv7a.rs
  probe-rs/src/architecture/arm/core/armv8a.rs
  probe-rs/src/architecture/riscv/communication_interface.rs
  probe-rs/src/architecture/riscv/dtm/jtag_dtm.rs
  probe-rs/src/architecture/riscv/mod.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/dap_types.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/protocol.rs
  probe-rs/src/bin/probe-rs/cmd/debug.rs
  probe-rs/src/bin/probe-rs/util/common_options.rs
  probe-rs/src/bin/probe-rs/util/rtt.rs
  probe-rs/src/core.rs
  probe-rs/src/debug/debug_info.rs
  probe-rs/src/debug/stack_frame.rs
  probe-rs/src/error.rs
  probe-rs/src/flashing/builder.rs
  probe-rs/src/flashing/flash_algorithm.rs
  probe-rs/src/probe.rs
  probe-rs/src/probe/cmsisdap/commands/swo.rs
  probe-rs/src/probe/cmsisdap/mod.rs
  probe-rs/src/probe/espusbjtag/protocol.rs
  probe-rs/src/probe/ftdi/ftdaye/mod.rs
  probe-rs/src/probe/jlink/mod.rs
  probe-rs/src/probe/jlink/speed.rs
  probe-rs/src/probe/stlink/mod.rs
  probe-rs/src/rtt.rs
  smoke-tester/src/dut_definition.rs
Labels: skip-changelog

#2223 Debug: Improve breakpoints and debug stepping behavior
  probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
  probe-rs/src/debug/debug_info.rs
  probe-rs/src/debug/debug_step.rs
  probe-rs/src/debug/language/c.rs
  probe-rs/src/debug/language/parsing.rs
  probe-rs/src/debug/language/rust.rs
  probe-rs/src/debug/language/value.rs
  probe-rs/src/debug/mod.rs
  probe-rs/src/debug/source_instructions.rs
  probe-rs/src/debug/unit_info.rs
  probe-rs/src/debug/variable.rs
Labels: skip-changelog
