Repository probe-rs/probe-rs, pull requests merged in 2024-01, with the labels that each got.

#1998 Don't serialize the default transfer encoding
  probe-rs-target/src/chip.rs
  probe-rs-target/src/flash_algorithm.rs
  probe-rs/src/flashing/flash_algorithm.rs
Labels: skip-changelog

#2000 Use a timeout while waiting for debug module to power on, recognise X…
  probe-rs/src/architecture/xtensa/xdm.rs
  probe-rs/src/probe/ftdi/mod.rs
Labels: skip-changelog

#1999 Enable ftdi when using ftdi-vendored
  changelog/changed-vendored-ftdi.md
  probe-rs/Cargo.toml
Labels: probe:ftdi, component:probe-rs

#2004 Fix clippy warnings added in 1.75
  probe-rs-target/src/chip_family.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/adapter.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/repl_commands.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/debug_adapter/dap/repl_commands_helpers.rs
  probe-rs/src/bin/probe-rs/util/rtt.rs
  probe-rs/src/probe/espusbjtag/protocol.rs
  probe-rs/src/probe/stlink/tools.rs
  probe-rs/src/session.rs
Labels: skip-changelog

#2006 FTDI: don't scan twice
  probe-rs/src/probe/ftdi/mod.rs
Labels: skip-changelog, probe:ftdi

#2005 espusbjtag: send proper BYPASS bits
  probe-rs/src/probe/espusbjtag/mod.rs
Labels: skip-changelog, probe:espusbjtag

#2009 Fix some kinks in the release flow and add PR info to changes
  xtask/src/main.rs
Labels: skip-changelog

#2010 Make CI set the token for the API access in the release pipeline prop…
  .github/workflows/start-release.yml
Labels: skip-changelog

#2013 Fix newlines in changelog
  xtask/src/main.rs
Labels: skip-changelog

#2019 Remove test feature
  Cargo.lock
  probe-rs/Cargo.toml
  probe-rs/src/bin/probe-rs/cmd/dap_server/server/debugger.rs
  probe-rs/src/bin/probe-rs/cmd/dap_server/test.rs
  probe-rs/src/bin/probe-rs/util/common_options.rs
  probe-rs/src/integration.rs
  probe-rs/src/lib.rs
  probe-rs/tests/flash_dry_run.rs
Labels: skip-changelog

#2020 Allow workflow dispatch for release builds
  .github/workflows/release.yml
Labels: skip-changelog

#2021 Revert "Allow workflow dispatch for release builds"
  .github/workflows/release.yml
Labels: skip-changelog

#2017 Xtensa: replace more untyped debug register ops
  probe-rs/src/architecture/xtensa/xdm.rs
Labels: skip-changelog

#2024 espusbjtag, ftdi: Fix JTAG IR measurement
  changelog/fixed-jtag-measurement.md
  probe-rs/src/probe/common.rs
  probe-rs/src/probe/espusbjtag/mod.rs
  probe-rs/src/probe/ftdi/mod.rs
Labels: skip-changelog

#2022 Make probe-rs info work with Xtensa
  changelog/added-xtensa-info.md
  probe-rs/src/architecture/xtensa/communication_interface.rs
  probe-rs/src/architecture/xtensa/xdm.rs
  probe-rs/src/bin/probe-rs/cmd/info.rs
Labels: skip-changelog

#1996 Split out `ProbeDriver`
  changelog/changed-debug-probe-traits.md
  changelog/removed-debugprobetype.md
  probe-rs/src/bin/probe-rs/cmd/dap_server/server/debugger.rs
  probe-rs/src/lib.rs
  probe-rs/src/probe.rs
  probe-rs/src/probe/arm_jtag.rs
  probe-rs/src/probe/cmsisdap/mod.rs
  probe-rs/src/probe/cmsisdap/tools.rs
  probe-rs/src/probe/espusbjtag/mod.rs
  probe-rs/src/probe/espusbjtag/protocol.rs
  probe-rs/src/probe/fake_probe.rs
  probe-rs/src/probe/ftdi/mod.rs
  probe-rs/src/probe/jlink/mod.rs
  probe-rs/src/probe/list.rs
  probe-rs/src/probe/stlink/mod.rs
  probe-rs/src/probe/stlink/tools.rs
  probe-rs/src/probe/stlink/usb_interface.rs
  probe-rs/src/probe/wlink/mod.rs
  probe-rs/src/probe/wlink/usb_interface.rs
Labels: skip-changelog, hygiene

#2028 Update ahash from 0.7.6 to 0.7.7 in Cargo.lock
  Cargo.lock
Labels: skip-changelog

#2029 Fix GITHUB_TOKEN env var name
  .github/workflows/start-release.yml
  xtask/src/main.rs
Labels: skip-changelog, ci

#2026 Use `extract_idcode` more
  probe-rs/src/probe.rs
  probe-rs/src/probe/cmsisdap/mod.rs
  probe-rs/src/probe/common.rs
  probe-rs/src/probe/espusbjtag/mod.rs
  probe-rs/src/probe/ftdi/mod.rs
Labels: skip-changelog, hygiene

#2042 cmsisdap: fix probes not being found on windows.
  probe-rs/src/probe/cmsisdap/tools.rs
Labels: skip-changelog

#2025 Align jlink and espusbjtag impls, clean up
  .github/workflows/smoketest.yml
  changelog/changed-jlink-multiple-taps.md
  probe-rs/src/architecture/riscv/dtm.rs
  probe-rs/src/architecture/xtensa/xdm.rs
  probe-rs/src/probe/cmsisdap/mod.rs
  probe-rs/src/probe/common.rs
  probe-rs/src/probe/espusbjtag/mod.rs
  probe-rs/src/probe/espusbjtag/protocol.rs
  probe-rs/src/probe/jlink/mod.rs
Labels: probe:jlink, hygiene

#2043 cmsisdap: use `get_string_descriptor` instead of doing a control request manually.
  probe-rs/src/probe/cmsisdap/tools.rs
Labels: skip-changelog

#2044 espusbjtag: use nusb `get_descriptor()` instead of doing a manual control request.
  probe-rs/src/probe/espusbjtag/protocol.rs
  probe-rs/src/probe/usb_util.rs
Labels: skip-changelog

#2049 Ftdi: do not discard devices without product string
  probe-rs/src/probe/ftdi/mod.rs
Labels: skip-changelog, probe:ftdi

#2048 JTAG state machine fixes
  probe-rs/src/probe/common.rs
  probe-rs/src/probe/espusbjtag/mod.rs
Labels: bug, probe:jlink, skip-changelog, probe:espusbjtag

#2051 Xtensa: hide private parts
  changelog/removed-private-xtensa.md
  probe-rs/examples/xtensa.rs
  probe-rs/src/architecture/xtensa/arch/instruction/format.rs
  probe-rs/src/architecture/xtensa/arch/instruction/mod.rs
  probe-rs/src/architecture/xtensa/mod.rs
Labels: hygiene, architecture:xtensa

#2059 `info`: Extract error printing, log starting a new phase
  probe-rs/src/bin/probe-rs/cmd/info.rs
Labels: skip-changelog

#2065 cmsisdap: don't do i/o for the iface string when listing devices.
  Cargo.lock
  probe-rs/Cargo.toml
  probe-rs/src/probe/cmsisdap/tools.rs
Labels: skip-changelog

#2057 Speed up J-Link JTAG
  probe-rs/src/probe/jlink/jaylink/mod.rs
  probe-rs/src/probe/jlink/mod.rs
Labels: protocol:jtag, probe:jlink, skip-changelog

#2060 Don't eagerly send out IR scan, clean up register access
  probe-rs/src/probe.rs
  probe-rs/src/probe/espusbjtag/mod.rs
Labels: skip-changelog, probe:espusbjtag

#2064 arch/arm: some adi_v5_memory_interface simplifications.
  probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
Labels: skip-changelog

#2016 The Big FTDI Rewrite
  probe-rs/src/architecture/riscv/communication_interface.rs
  probe-rs/src/architecture/xtensa/communication_interface.rs
  probe-rs/src/architecture/xtensa/xdm.rs
  probe-rs/src/probe.rs
  probe-rs/src/probe/espusbjtag/mod.rs
  probe-rs/src/probe/ftdi/command_compacter.rs
  probe-rs/src/probe/ftdi/commands.rs
  probe-rs/src/probe/ftdi/mod.rs
Labels: skip-changelog, probe:ftdi

#2062 Reuse the probe driver's idle cycle mechanism, allocate less
  probe-rs/src/architecture/arm/communication_interface.rs
  probe-rs/src/probe/arm_jtag.rs
Labels: skip-changelog

#2068 Various fixes
  probe-rs/src/architecture/riscv/communication_interface.rs
  probe-rs/src/architecture/riscv/dtm.rs
  probe-rs/src/architecture/riscv/mod.rs
  probe-rs/src/architecture/xtensa/communication_interface.rs
  probe-rs/src/architecture/xtensa/xdm.rs
  probe-rs/src/bin/probe-rs/cmd/info.rs
  probe-rs/src/session.rs
Labels: skip-changelog

#2066 Delete duplicate JTAG logic
  probe-rs/src/probe.rs
  probe-rs/src/probe/arm_jtag.rs
  probe-rs/src/probe/common.rs
  probe-rs/src/probe/espusbjtag/mod.rs
  probe-rs/src/probe/espusbjtag/protocol.rs
  probe-rs/src/probe/ftdi/mod.rs
  probe-rs/src/probe/jlink/mod.rs
  probe-rs/src/probe/wlink/mod.rs
Labels: skip-changelog

#2083 Reuse ProbeOptions in cargo-embed
  probe-rs/src/bin/probe-rs/cmd/cargo_embed/mod.rs
  probe-rs/src/bin/probe-rs/util/common_options.rs
  probe-rs/src/probe.rs
Labels: skip-changelog

#2084 arch/arm: add 64bit block transfers, to make it consistent with smaller ones.
  probe-rs/src/architecture/arm/memory/adi_v5_memory_interface.rs
Labels: skip-changelog

#2086 probe: centralize "device matches selector" logic.
  probe-rs/src/probe.rs
  probe-rs/src/probe/cmsisdap/tools.rs
  probe-rs/src/probe/espusbjtag/protocol.rs
  probe-rs/src/probe/ftdi/mod.rs
  probe-rs/src/probe/jlink/mod.rs
  probe-rs/src/probe/stlink/usb_interface.rs
  probe-rs/src/probe/wlink/usb_interface.rs
Labels: skip-changelog

#2088 Update all deps and clean version numbers
  Cargo.lock
  Cargo.toml
  probe-rs/Cargo.toml
  probe-rs/src/probe/jlink/jaylink/macros.rs
  probe-rs/src/probe/jlink/jaylink/mod.rs
  rtthost/Cargo.toml
  xtask/Cargo.toml
Labels: skip-changelog

#2087 probe/jlink: cleanup.
  probe-rs/src/probe/jlink/bits.rs
  probe-rs/src/probe/jlink/capabilities.rs
  probe-rs/src/probe/jlink/error.rs
  probe-rs/src/probe/jlink/interface.rs
  probe-rs/src/probe/jlink/jaylink/bits.rs
  probe-rs/src/probe/jlink/jaylink/error.rs
  probe-rs/src/probe/jlink/jaylink/mod.rs
  probe-rs/src/probe/jlink/macros.rs
  probe-rs/src/probe/jlink/mod.rs
  probe-rs/src/probe/jlink/speed.rs
  probe-rs/src/probe/jlink/swo.rs
Labels: skip-changelog

#2094 Recommend binary instalation for tools
  README.md
Labels: skip-changelog

#2095 Remove `FlashAlgorithm::begin_data`
  changelog/removed-flash-algorithm-begin-data.md
  probe-rs/src/flashing/flash_algorithm.rs
  probe-rs/src/flashing/flasher.rs
Labels: hygiene

#2101 stlink: use hex-encoded serial to match selectors.
  probe-rs/src/probe/stlink/usb_interface.rs
Labels: skip-changelog

#2113 Use WARN as the default log level
  probe-rs/src/bin/probe-rs/util/logging.rs
Labels: skip-changelog

#2114 Rename the arm_jtag module to arm_debug_interface
  probe-rs/src/architecture/arm/dp/mod.rs
  probe-rs/src/probe.rs
  probe-rs/src/probe/arm_debug_interface.rs
  probe-rs/src/probe/ftdi/mod.rs
  probe-rs/src/probe/jlink/mod.rs
Labels: skip-changelog

#2117 Use new M1 runners, update cargo-dist
  .github/workflows/ci.yml
  .github/workflows/release.yml
  Cargo.toml
Labels: skip-changelog
