Repository probe-rs/probe-rs, pull requests merged in 2024-09, with the labels that each got.

#2732 Fix compatibility with clone J-Link devices
  changelog/fixed-jlink-clone.md
  probe-rs/src/probe/jlink/config.rs
  probe-rs/src/probe/jlink/connection.rs
  probe-rs/src/probe/jlink/mod.rs
  probe-rs/src/probe/jlink/speed.rs
  probe-rs/src/probe/jlink/swo.rs
Labels: enhancement, probe:jlink

#2728 ST-Link: Deduplicate memory read/write command serialization, clean up port switching
  probe-rs/src/probe/stlink/mod.rs
Labels: skip-changelog

#2795 Fix RTT when downloading to RAM
  probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/mod.rs
  probe-rs-tools/src/bin/probe-rs/cmd/run/mod.rs
  probe-rs/src/flashing/loader.rs
Labels: skip-changelog

#2807 Update bitfield to 0.17.0
  Cargo.lock
  probe-rs/Cargo.toml
  probe-rs/src/core/memory_mapped_registers.rs
Labels: skip-changelog

#2808 Fix ESP32-C3 once again
  probe-rs/src/architecture/riscv/communication_interface.rs
  probe-rs/src/vendor/espressif/mod.rs
  probe-rs/src/vendor/espressif/sequences/esp32c2.rs
  probe-rs/src/vendor/espressif/sequences/esp32c3.rs
Labels: skip-changelog

#2815 Clarify the CMSIS DAP error enum reason and location of error
  probe-rs/src/probe/cmsisdap/commands/jtag/configure.rs
  probe-rs/src/probe/cmsisdap/commands/mod.rs
  probe-rs/src/probe/cmsisdap/commands/swd/configure.rs
  probe-rs/src/probe/cmsisdap/commands/swj/clock.rs
  probe-rs/src/probe/cmsisdap/commands/swo.rs
  probe-rs/src/probe/cmsisdap/commands/transfer/configure.rs
  probe-rs/src/probe/cmsisdap/commands/transfer/mod.rs
  probe-rs/src/probe/cmsisdap/mod.rs
Labels: skip-changelog

#2819 Simplify ESP flash attach and handle SPI config where needed
  probe-rs/src/architecture/riscv/assembly.rs
  probe-rs/src/architecture/riscv/communication_interface.rs
  probe-rs/src/vendor/espressif/mod.rs
  probe-rs/src/vendor/espressif/sequences/esp.rs
  probe-rs/src/vendor/espressif/sequences/esp32.rs
  probe-rs/src/vendor/espressif/sequences/esp32c2.rs
  probe-rs/src/vendor/espressif/sequences/esp32c3.rs
  probe-rs/src/vendor/espressif/sequences/esp32c6.rs
  probe-rs/src/vendor/espressif/sequences/esp32h2.rs
  probe-rs/src/vendor/espressif/sequences/esp32s2.rs
  probe-rs/src/vendor/espressif/sequences/esp32s3.rs
Labels: skip-changelog

#2776 Make progress bars constant width
  probe-rs-tools/src/bin/probe-rs/util/flash.rs
Labels: bug, skip-changelog

#2821 J-Link: Allowlist register_connection for known devices
  probe-rs/src/probe/jlink/mod.rs
Labels: skip-changelog
